main_sucursal:
    resource: "@MainBundle/Resources/config/routing/sucursal.yml"
    prefix:   /sucursal

main_home:
    path:     /
    defaults: { _controller: MainBundle:Default:index }
    
main_sucursales:
    path:     /sucursales
    defaults: { _controller: MainBundle:Default:sucursales }
    
main_compra:
    resource: "@MainBundle/Resources/config/routing/compra.yml"
    prefix:   /compra
    
main_inventario:
    resource: "@MainBundle/Resources/config/routing/inventario.yml"
    prefix:   /inventario
