services:
    main_compra_repositorio:
        class: MainBundle\Repository\CompraRepositorio
        arguments: [@doctrine]

    main_mercaderia_repositorio:
        class: MainBundle\Repository\MercaderiaRepositorio
        arguments: [@doctrine]

    main_rubro_repositorio:
        class: MainBundle\Repository\RubroRepositorio
        arguments: [@doctrine]
        
    main_proveedor_repositorio:
        class: MainBundle\Repository\ProveedorRepositorio
        arguments: [@doctrine]
        
    main_inventario_repositorio:
        class: MainBundle\Repository\InventarioRepositorio
        arguments: [@doctrine]